development:
  adapter: mysql
  encoding: utf8
  database: tuffrails_dev
  username: root
  password: w0jt3k
  socket: /var/run/mysqld/mysqld.sock


test:
  adapter: mysql
  encoding: utf8
  database: tuffrails_test
  username: root
  password: w0jt3k
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  database: tuffrails_production
  username: root
  password: w0jt3k
  socket: /var/run/mysqld/mysqld.sock
